fatal: not a git repository (or any of the parent directories): .git

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
[Fri Sep 30 11:15:26.937464 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024] [2022-09-30 11:15:26,929] ERROR in app: Exception on /admin/reload [GET]
[Fri Sep 30 11:15:26.937556 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024] Traceback (most recent call last):
[Fri Sep 30 11:15:26.937577 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
[Fri Sep 30 11:15:26.937596 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     response = self.full_dispatch_request()
[Fri Sep 30 11:15:26.937615 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Fri Sep 30 11:15:26.937630 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     rv = self.handle_user_exception(e)
[Fri Sep 30 11:15:26.937644 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Fri Sep 30 11:15:26.937658 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     rv = self.dispatch_request()
[Fri Sep 30 11:15:26.937676 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
[Fri Sep 30 11:15:26.937697 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Fri Sep 30 11:15:26.937711 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/app.py", line 80, in token_dec
[Fri Sep 30 11:15:26.937725 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     return f(id=username, *args, **kwargs)
[Fri Sep 30 11:15:26.937739 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/app.py", line 91, in admin_dec
[Fri Sep 30 11:15:26.937753 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     return f(*args, **kwargs)
[Fri Sep 30 11:15:26.937767 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/app.py", line 289, in reload
[Fri Sep 30 11:15:26.937785 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024]     return str(res), 200
[Fri Sep 30 11:15:26.937798 2022] [wsgi:error] [pid 1588:tid 3034960896] [remote 85.138.78.7:1024] NameError: name 'res' is not defined
fatal: not a git repository (or any of the parent directories): .git

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
[Fri Sep 30 11:15:49.977822 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024] [2022-09-30 11:15:49,969] ERROR in app: Exception on /admin/reload [GET]
[Fri Sep 30 11:15:49.977908 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024] Traceback (most recent call last):
[Fri Sep 30 11:15:49.977925 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
[Fri Sep 30 11:15:49.977941 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     response = self.full_dispatch_request()
[Fri Sep 30 11:15:49.977995 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Fri Sep 30 11:15:49.978011 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     rv = self.handle_user_exception(e)
[Fri Sep 30 11:15:49.978026 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Fri Sep 30 11:15:49.978040 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     rv = self.dispatch_request()
[Fri Sep 30 11:15:49.978054 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/virtualenv/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
[Fri Sep 30 11:15:49.978069 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Fri Sep 30 11:15:49.978084 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/app.py", line 80, in token_dec
[Fri Sep 30 11:15:49.978098 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     return f(id=username, *args, **kwargs)
[Fri Sep 30 11:15:49.978112 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/app.py", line 91, in admin_dec
[Fri Sep 30 11:15:49.978126 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     return f(*args, **kwargs)
[Fri Sep 30 11:15:49.978140 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]   File "/home/ruipires/Game/app.py", line 289, in reload
[Fri Sep 30 11:15:49.978154 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024]     return "Ok", 200
[Fri Sep 30 11:15:49.978168 2022] [wsgi:error] [pid 1588:tid 3001390080] [remote 85.138.78.7:1024] NameError: name 'res' is not defined
fatal: not a git repository (or any of the parent directories): .git

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
fatal: not a git repository (or any of the parent directories): .git

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
fatal: not a git repository (or any of the parent directories): .git

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
fatal: not a git repository (or any of the parent directories): .git

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
